language: go
go:
  - 1.14.x
  - 1.15.x
  - tip
arch:
  - amd64
  - ppc64le
before_install:
  - go get -u github.com/vbatts/git-validation

stages:
  - validate
  - build
  - lint
  - test

jobs:
  include:
    - stage: build
      script: make

    - stage: lint
      script: make lint BUILDTAGS=""

    - stage: test
      script: make test BUILDTAGS=""

    - stage: validate
#POWERON SUPPORT 
    - stage: build
      script: make
      arch: ppc64le
    - stage: lint
      script: make lint BUILDTAGS=""
      arch: ppc64le
    - stage: test
      script: make test BUILDTAGS=""
      arch: ppc64le
      go:  1.14.x
    - stage: test
      script: make test BUILDTAGS=""
      arch: ppc64le
      go: 1.15.x
    - stage: test
      script: make test BUILDTAGS=""
      arch: ppc64le
      go : tip
    - stage: validate
      arch: ppc64le

      script: |
        git-validation -run DCO,short-subject -v -range ${TRAVIS_COMMIT_RANGE}
