language: go
go:
  - 1.14.x
  - 1.15.x
  - tip
arch:
  - amd64
  - ppc64le
before_install:
  - go get -u github.com/vbatts/git-validation

stages:
  - validate
  - build
  - lint
  - test

jobs:
  include:
    - stage: build
      script: make

    - stage: lint
      script: make lint BUILDTAGS=""

    - stage: test
      script: make test BUILDTAGS=""

    - stage: validate
    
script: |
        git-validation -run DCO,short-subject -v -range ${TRAVIS_COMMIT_RANGE}
